Name: kits
Main: XoticRealmsOwnerandDev\kits\kits.php
Aurthor: XoticRealmsOwnerandDev
Version: 1.0
API: [2.0.0]
Description: gives a player a kit when they run the command

Commands:
      kit: 
       usage: /kit <KitName>
       description: gives a player a kit
       permission: kit.use
permissions:
           kit:
               default: false
               description: Allows the player to use all of the SimpleKits features
               children:
                     kit.use:
                           default: false
                           description: Allows the player to use the Kit command
